name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [dev, prod, stage] 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directory for key
        run: mkdir -p ~/terraform

      - name: Create empty key file (optional)
        run: touch ~/terraform/terraform_key.pub

      - name: Create public key file
        run: echo "${{ secrets.PUBLIC_SSH_KEY }}" > ~/terraform/terraform_key.pub

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Adjust to your Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: ./main

      - name: Select Workspace
        run: terraform workspace select ${{ matrix.workspace }} || terraform workspace new ${{ matrix.workspace }}
        working-directory: ./main

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./main

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./main

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        working-directory: ./main

      - name: Output EC2 Public IP
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform output ec2_public_ip
        working-directory: ./main
